### ISSUE TITLE
Great library. how this compare to FlightAnimator?

### ISSUE THREAD

**Issue by steve21124** [Trxy/TRX#1]
Thanks for the great library.  How this library compare to https://github.com/AntonTheDev/FlightAnimator ? I like, it is based on GAPS. What feature TRX has and FlightAnimator does not has?

**Comment by modzelewski** [comment]
Thanks Steve, that's a good question. While FlightAnimator uses CoreAnimation under the hood and focuses on creating a domain specific language for it (which it does very well), TRX has a different approach. It allows to easily animate any numeric property on any entity not just the ones that are [CA Animatable](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/CoreAnimation_guide/AnimatableProperties/AnimatableProperties.html) and on a CALayer.

It also introduces the concept of Timelines that let you group and overlap Tweens as well as other Timelines (which you might know form GSAP). 

TRX strives to make animations fully interactive, so it's ease to pause, seek/scrub and squeeze single Tweens as well as entire Timelines.

**Comment by steve21124** [comment]
Thanks for great explanation. I will definitely try it out.
