### ISSUE TITLE
Add some explanations

### ISSUE THREAD

**Issue by ghost** [Trxy/TRX#2]
This is hard to understand the main principle of TRX. e.g what does the number _1_ before the dots in `1.trx(to: 20) { object.value = $0 }.start()` means?  

And where is the _time_ value in the neater way of the basic usage?

```
Tween(from: 0, to: 20, time: 0.3) {
  object.value = $0
}.start()
```
Or, neater...

```
1.trx(to: 20) { object.value = $0 }.start()
```

Thus I think documentation should be helpful!

**Comment by modzelewski** [comment]
Thanks for your feedback @Domsware. Sure, a better explanation would be great. If you have an idea how to phrase it better, feel free to create a pull request.
